### ISSUE TITLE
Update of the plugin

### ISSUE THREAD

**Issue by ChuZhenMok** [RafhaanShah/TaskerHealthConnect#1]
Hi, I just found your Tasker Plugin for Health Connect.
I am wondering if you will continue to update the plugin?
There is no other way to extract health data from Health Connect to Tasker that I can find.
Joao said this is not in his list for native Tasker data for the near future.
I really hope you will continue to update the plugin.
Thank you.

**Comment by RafhaanShah** [comment]
Hello, which information are you looking to extract?

**Comment by ChuZhenMok** [comment]
Thank you for your prompt response. I have a few clarifying questions:

1. When does the "days back to aggregate" period begin? Is it 24 hours from now, or from 12 am today?
2. Is it possible to extract data for sleep, oxygen saturation, resting heart rate, floor climbed, and distance?

I understand that this is a lot to ask, but I would be grateful if you could consider adding these data types.

Thank you again for your work.

**Comment by RafhaanShah** [comment]
Hey sorry for the late response, I will try to add the new data types when I have some time to update the plugin. As for your questions:

1. It's based on "now". E.g. "days back = 1" would be data `from now minus 1 day` -> `to now`
2. If this data is accessible via standard Health Connect APIs then it should be possible

**Comment by Nefari0uss** [comment]
I'd love to see an update to this to support more data! I haven't glanced at the Health Connect APIs although I'm guessing that you can provide field to pull data from such as "Sleep", "Weight", "VO2 max", "Heart rate", etc? 

Edit: Looking through the HC app, it seems like the data is aggregated into broad categories such as "Body measurements", "Sleep", etc, and from there you can go into more detailed sections such as "Body fat", "Height", "Weight".

My thoughts are that the two most useful bits of data would be the items that Google Fit and Samsung Health can write to Health Connect for.

**Comment by RafhaanShah** [comment]
Added fetching all of the aggregated data types currently available in [0.0.2](https://github.com/RafhaanShah/TaskerHealthConnect/releases/tag/0.0.2)

And just to make the "days back" more clear, when it's `0`, it will fetch all the data for "today", so from midnight today until right now. When it's `1`, it will subtract 1 day from midnight of today, and fetch from there (so `1` would be from midnight yesterday until now)
