### ISSUE TITLE
More user friendly UI

### ISSUE THREAD

**Issue by rodrigoswz** [RafhaanShah/TaskerHealthConnect#10]
Any plans to make it for easy use?

Something like a **Get Health Connect Data** task, that I can easily choose _Steps_ (for example) and store that in a variable? And set default units (km, mi...).

From what I understand, I can currently obtain a JSON with several unconverted data. Honestly, I was happy to find this plugin but I still haven't been able to use it perfectly.

**Comment by RafhaanShah** [comment]
No plans to add specific Tasker actions for each individual data type (as that would be quite duplicative for the 30+ data types)

The Plugin focuses on JSON at the moment as there's a variety of different fields for each record type, and this approach avoids having to add specific logic for each record type, and Tasker supports [reading JSON](https://tasker.joaoapps.com/userguide/en/variables.html) natively

These values are already converted, you can see the conversions and units in the [HealthConnectRepository](https://github.com/RafhaanShah/TaskerHealthConnect/blob/main/app/src/main/java/com/rafapps/taskerhealthconnect/HealthConnectRepository.kt#L131) file, but choosing units is something I'll look to do in the future

I do agree that this is a more advanced plugin than some others, but it does cover the use-case of fetching any data type from Health Connect from a specified time :) I'd look at https://developer.android.com/health-and-fitness/guides/health-connect/test/health-connect-toolbox if you want to understand more about the underlying data
