### ISSUE TITLE
Version v0.0.5 is still tagged as v.0.0.4 in build.gradle

### ISSUE THREAD

**Issue by tadwohlrapp** [RafhaanShah/TaskerHealthConnect#11]
Seems like the version number was overlooked in the current v0.0.5 release. See lines here:
https://github.com/RafhaanShah/TaskerHealthConnect/blob/8ff36b05e544ad6c75d9d64125cbb12617615a2d/app/build.gradle#L14-L15

**Comment by RafhaanShah** [comment]
Yeah I forget to update it, I've added #9 to fix this for the future, PRs are welcome :)
