### ISSUE TITLE
Abnormal calorie count

### ISSUE THREAD

**Issue by MAGNUMhere** [RafhaanShah/TaskerHealthConnect#13]
When i pulling the calories data to tasker, it's giving in millions, am i missing something or it is actually wrong data.

"BasalMetabolicRateRecord_BASAL_CALORIES_TOTAL":1649193.3324504,
"TotalCaloriesBurnedRecord_ENERGY_TOTAL":1725825.5371496629

**Comment by RafhaanShah** [comment]
Can you compare the data for the exact same time range with the Health Connect Toolbox mentioned in the readme, and add the full output of both, formatted properly

**Comment by MAGNUMhere** [comment]
This is the following data i get when i pull it from tasker, it is aggregate data of 1 day ago
I've also checked the data in health connect tool box 
![Screenshot_2024-09-06-17-32-18-519_androidx health connect client devtool](https://github.com/user-attachments/assets/f3c4873e-bccf-4f18-ac5b-722e2277d56e)


[{"startTime":"2024-09-04T18:30:00.061Z","endTime":"2024-09-05T18:30:00.061Z","ExerciseSessionRecord_EXERCISE_DURATION_TOTAL":14,"SleepSessionRecord_SLEEP_DURATION_TOTAL":356,"BasalMetabolicRateRecord_BASAL_CALORIES_TOTAL":1649193.3324504,"TotalCaloriesBurnedRecord_ENERGY_TOTAL":1721060.084339048,"DistanceRecord_DISTANCE_TOTAL":1030.4000244140625,"HeartRateRecord_BPM_AVG":102,"HeartRateRecord_BPM_MIN":51,"HeartRateRecord_BPM_MAX":114,"HeartRateRecord_MEASUREMENTS_COUNT":798,"StepsRecord_COUNT_TOTAL":6783},{"startTime":"2024-09-05T18:30:00.061Z","endTime":"2024-09-06T18:30:00.061Z","SleepSessionRecord_SLEEP_DURATION_TOTAL":572,"BasalMetabolicRateRecord_BASAL_CALORIES_TOTAL":1649193.3324504,"TotalCaloriesBurnedRecord_ENERGY_TOTAL":1649193.3324504,"HeartRateRecord_BPM_AVG":71,"HeartRateRecord_BPM_MIN":60,"HeartRateRecord_BPM_MAX":95,"HeartRateRecord_MEASUREMENTS_COUNT":72,"StepsRecord_COUNT_TOTAL":3350},{"startTime":"2024-09-06T18:30:00.061Z","endTime":"2024-09-07T12:05:10.064Z","BasalMetabolicRateRecord_BASAL_CALORIES_TOTAL":1208454.106771005,"TotalCaloriesBurnedRecord_ENERGY_TOTAL":1208454.106771005}]

**Comment by RafhaanShah** [comment]
You're using the wrong option on the health connect toolbox, you need to go to "Read Aggregate Data" for aggregate data, which is what the output from the Tasker plugin is.

Also the plugin outputs in `Calories` not `KiloCalories` that's why the number seems high, divide by 1000 to get KCal

**Comment by MAGNUMhere** [comment]
Thank you for the clarification, but still I'm getting the data wrong,
I'm using samsung health app to get the health data, when i compare samsung health data with health connect toolbox data they doesn't match 
![Screenshot_2024-09-10-03-05-10-866_com sec android app shealth](https://github.com/user-attachments/assets/22d4ff28-898c-4a41-9d38-866de580696c)
![Screenshot_2024-09-10-03-05-01-676_androidx health connect client devtool](https://github.com/user-attachments/assets/ca1467d4-540a-4ee2-830b-b8d4767dd3ab)

**Comment by RafhaanShah** [comment]
That doesn't really have anything to do with this Tasker plugin though, that's just a discrepancy between Samsung Health and Health Connect. Not really anything I can do about that 🤷
