### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by izakfab** [RafhaanShah/TaskerHealthConnect#3]
When I launch an app and try to grant it premissions I get a message from Health connect, that Tasker Health Connect needs an update.

**Comment by danguno** [comment]
Same here, I think because Health Connect on Android 14 is integrated differently than on previous versions of the OS.

**Comment by RafhaanShah** [comment]
Hey yes will look into this in the next update along with more data types

**Comment by RafhaanShah** [comment]
Fixed in release [0.0.2](https://github.com/RafhaanShah/TaskerHealthConnect/releases/tag/0.0.2)
