### ISSUE TITLE
Current day step count is wrong

### ISSUE THREAD

**Issue by izakfab** [RafhaanShah/TaskerHealthConnect#5]
When I pull the current day data for the step count, it is lower than shown in the health connect app. I think, that it is connected to percentage of the day passed, because if I divide the value, pulled using the plugin, with the percentage of the day passed (0.5 for 12:00, 0.33 for 8:00, 0.75 for 18:00, etc.). But wierdly enough, I get a little bit of difference ± 100-ish steps, when I calculate the actual steps.

**Comment by RafhaanShah** [comment]
Can you add the JSON output and some screenshots of the health connect app data for the same day

**Comment by izakfab** [comment]
The JSON output is: [{"startTime":"2024-03-14T23:00:00.074Z","endTime":"2024-03-15T21:39:37.075Z","SleepSessionRecord_SLEEP_DURATION_TOTAL":332,"BasalMetabolicRateRecord_BASAL_CALORIES_TOTAL":1515608.945605937,"TotalCaloriesBurnedRecord_ENERGY_TOTAL":1515608.945605937,"HeartRateRecord_BPM_AVG":73,"HeartRateRecord_BPM_MIN":46,"HeartRateRecord_BPM_MAX":120,"HeartRateRecord_MEASUREMENTS_COUNT":1124,"StepsRecord_COUNT_TOTAL":10664}]

The screenshot is:
![Screenshot_20240315_223957_HealthConnect.jpg](https://github.com/RafhaanShah/TaskerHealthConnect/assets/92325936/17227fab-69eb-4280-b332-605ec767f00b)

The time was 22:39 which is roughly 94.375% of the day 
10664÷0.94375=112999 which is close to the value shown in the app.

**Comment by RafhaanShah** [comment]
Thanks! Does the step count for other days match up?

Do other data types like calories or sleep duration or heart rate data for today/ other days match?

**Comment by izakfab** [comment]
For other days it works as intended and I can check for calories later in the day, as it was just midnight over here.

**Comment by izakfab** [comment]
Okay that's wierd. In the health connect app there isn't any data for calories at all.

![Screenshot_20240316_104516_HealthConnect.jpg](https://github.com/RafhaanShah/TaskerHealthConnect/assets/92325936/c4c136e3-3df8-4ed9-932d-9543dc184433)

But in the JSON output (seen in one of my previous comments) there is some value.

**Comment by RafhaanShah** [comment]
Try comparing data with https://goo.gle/health-connect-toolbox

**Comment by izakfab** [comment]
> Try comparing data with https://goo.gle/health-connect-toolbox 

![Screenshot_20240318_174039_Health Connect Toolbox.jpg](https://github.com/RafhaanShah/TaskerHealthConnect/assets/92325936/5e79a7b9-07c9-4993-b1cb-433b4ef0e923)

![Screenshot_20240318_174129_HealthConnect.jpg](https://github.com/RafhaanShah/TaskerHealthConnect/assets/92325936/158089e4-4129-4efa-9b20-dc8335b31a56)



Health connect toolbox doesnt read any steps data for today, even though there are steps in Health connect.

**Comment by RafhaanShah** [comment]
The toolbox screenshot says it's from 12pm, not 12am?

Trying to see if the data is inaccurate just for today, or for every day, and if it's just steps or other data tok
