### ISSUE TITLE
[Feature Request] Read Health Record

### ISSUE THREAD

**Issue by eliasacab** [RafhaanShah/TaskerHealthConnect#6]
I have a smart blood pressure monitor that can upload results to Health Connect, however, using the Health Connect Toolbox > Read Aggregate Data > BloodPressure function results in "Unsupported aggregation type BloodPressure_diastolic_avg"

But if I use the Read Health Record > BloodPressure function, I can get the values.

Would it be possible to add a "Read Health Record" option to this Tasker Plugin?
Thank you!

**Comment by RafhaanShah** [comment]
Hey there, sure I'll have a look into adding single health record fetching when I have some time

**Comment by RafhaanShah** [comment]
Hey @eliasacab question about your use-case, which of these options seems most convenient

1. Input a startTime and endTime (as a unix timestamp / epoch milliseconds, such as Tasker's %TIMEMS)
2. Input a startTime only, so it's assumed that the endTime will always be "now"
3. Input a daysBack number, so it will fetch all records from midnight at "daysBack" days ago, until now 

I was thinking option 2 but was curious as to what people would find convenient

**Comment by eliasacab** [comment]
Yeah, number 2 makes sense, that should be able to pull the latest value(s), which is what I was hoping to do. Thanks!

**Comment by RafhaanShah** [comment]
Added in release 0.0.3, let me know how it works 😄

**Comment by eliasacab** [comment]
Hmm I'm getting an error when using BloodPressureRecord. I do get data when using the Toolbox app.


![Screenshot_20240427-114513](https://github.com/RafhaanShah/TaskerHealthConnect/assets/63508678/ea006688-7f8f-4564-9571-457b0b1839e5)

**Comment by RafhaanShah** [comment]
Oops, seemed ok when I was debugging, will take a look

**Comment by RafhaanShah** [comment]
[app-release.zip](https://github.com/RafhaanShah/TaskerHealthConnect/files/15140188/app-release.zip)

Ah might be something with obfuscation in the release version and I was using the debug version, can you try this APK?

**Comment by eliasacab** [comment]
It works with that apk! Thanks so much!

**Comment by RafhaanShah** [comment]
Great!
