### ISSUE TITLE
[Feature Request] Use variable in plugin

### ISSUE THREAD

**Issue by TheDuke777** [RafhaanShah/TaskerHealthConnect#7]
Hi! I'm loving the plugin so far, but would love to be able to use a variable to determine how far back to get data from.

**Comment by RafhaanShah** [comment]
Hey, yeah good point, I think Tasker variable substitution only works for String types, so will have to do some parsing there but should be straightforward

**Comment by RafhaanShah** [comment]
This should work in release 0.0.3, let me know if you have any issues 😄

**Comment by TheDuke777** [comment]
It works great for the task I've been working on! Thanks for the quick change!
